apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agenticsandboxclasses.model.skippy.io
spec:
  group: model.skippy.io
  scope: Cluster
  names:
    plural: agenticsandboxclasses
    singular: agenticsandboxclass
    kind: AgenticSandboxClass
    shortNames:
    - asclass
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: "AgenticSandboxClassSpec defines the desired state of AgenticSandboxClass. This is the template for creating sandbox instances."
              type: object
              required: ["image", "serverPort"]
              properties:
                image:
                  description: "Image is the container image for the sandbox environment."
                  type: string
                podSecurityContext:
                  description: "PodSecurityContext defines the security context to apply to the sandbox pods."
                  type: object
                  properties:
                    # Properties intentionally simplified for brevity in this example.
                    # The full schema is very large. x-kubernetes-preserve-unknown-fields
                    # allows any valid PodSecurityContext structure.
                    runAsUser:
                      type: integer
                      format: int64
                    runAsGroup:
                      type: integer
                      format: int64
                    runAsNonRoot:
                      type: boolean
                  x-kubernetes-preserve-unknown-fields: true
                resourceRequirements:
                  description: "ResourceRequirements are the standard Kubernetes resource requests and limits."
                  type: object
                  properties:
                    limits:
                      type: object
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                        x-kubernetes-int-or-string: true
                    requests:
                      type: object
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                        x-kubernetes-int-or-string: true
                runtimeClassName:
                  description: "RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group."
                  type: string
                serverPort:
                  description: "ServerPort is the internal port that the in-pod API server listens on."
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 65535
                tolerations:
                  description: "Tolerations are the Pod's tolerations."
                  type: array
                  items:
                    type: object
                    properties:
                      key: { type: string }
                      operator: { type: string }
                      value: { type: string }
                      effect: { type: string }
                      tolerationSeconds: { type: integer, format: int64 }
            status:
              type: object
              description: "Most recently observed status of the AgenticSandboxClass resource."
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status", "lastTransitionTime"]
                    properties:
                      type: { type: string }
                      status: { type: string }
                      lastTransitionTime: { type: string, format: date-time }
                      reason: { type: string }
                      message: { type: string }
                      observedGeneration: { type: integer, format: int64 }

