apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .resource.metadata.name }}
  namespace: {{ or .resource.metadata.namespace "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-{{ .resource.metadata.name }}
  template:
    metadata:
      labels:
        app: helloworld-{{ .resource.metadata.name }}
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay
        command: [ "cowsay" ]
        args: [ "Hello, World from {{ .resource.spec.message }}!" ]
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi