//go:build !ignore_autogenerated

/*
  File Header
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Integration) DeepCopyInto(out *Integration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make([]IntegrationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Integration.
func (in *Integration) DeepCopy() *Integration {
	if in == nil {
		return nil
	}
	out := new(Integration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Integration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationApiContextRequestSpec) DeepCopyInto(out *IntegrationApiContextRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationApiContextRequestSpec.
func (in *IntegrationApiContextRequestSpec) DeepCopy() *IntegrationApiContextRequestSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationApiContextRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationApiContextSpec) DeepCopyInto(out *IntegrationApiContextSpec) {
	*out = *in
	out.Request = in.Request
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationApiContextSpec.
func (in *IntegrationApiContextSpec) DeepCopy() *IntegrationApiContextSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationApiContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationApiHashSpec) DeepCopyInto(out *IntegrationApiHashSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationApiHashSpec.
func (in *IntegrationApiHashSpec) DeepCopy() *IntegrationApiHashSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationApiHashSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationApiReferencePathSpec) DeepCopyInto(out *IntegrationApiReferencePathSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationApiReferencePathSpec.
func (in *IntegrationApiReferencePathSpec) DeepCopy() *IntegrationApiReferencePathSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationApiReferencePathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationApiReferenceSpec) DeepCopyInto(out *IntegrationApiReferenceSpec) {
	*out = *in
	out.Paths = in.Paths
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationApiReferenceSpec.
func (in *IntegrationApiReferenceSpec) DeepCopy() *IntegrationApiReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationApiReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationApiTemplatesSpec) DeepCopyInto(out *IntegrationApiTemplatesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationApiTemplatesSpec.
func (in *IntegrationApiTemplatesSpec) DeepCopy() *IntegrationApiTemplatesSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationApiTemplatesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationList) DeepCopyInto(out *IntegrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Integration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationList.
func (in *IntegrationList) DeepCopy() *IntegrationList {
	if in == nil {
		return nil
	}
	out := new(IntegrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSpec) DeepCopyInto(out *IntegrationSpec) {
	*out = *in
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]IntegrationApiReferenceSpec, len(*in))
		copy(*out, *in)
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make([]IntegrationApiContextSpec, len(*in))
		copy(*out, *in)
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]IntegrationApiTemplatesSpec, len(*in))
		copy(*out, *in)
	}
	if in.Hashes != nil {
		in, out := &in.Hashes, &out.Hashes
		*out = make([]IntegrationApiHashSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSpec.
func (in *IntegrationSpec) DeepCopy() *IntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationStatus) DeepCopyInto(out *IntegrationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationStatus.
func (in *IntegrationStatus) DeepCopy() *IntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(IntegrationStatus)
	in.DeepCopyInto(out)
	return out
}
