apiVersion: model.skippy.io/v1
kind: Integration
metadata:
  name: skippy-integrations
spec:
  - group: model.skippy.io
    version: v1
    kind: Endpoint
    context:
      - name: model
        request:
          method: GET
          path: https://{{ .resource.spec.region }}-aiplatform.googleapis.com/v1/projects/{{ .resource.spec.project_id }}/locations/{{ .resource.spec.region }}/models/{{ .resource.spec.model_id }}@{{ or .resource.spec.version "default" }}
      - name: aire
        request:
          method: GET
          path: https://gkerecommender.googleapis.com/v1alpha1/accelerators?alt=json&modelName={{ urlEncodeModelName .resource.spec.model_name }}&modelServerName=ANY&modelServerVersion=LATEST&performanceRequirements.maxNtpotMilliseconds=999999
    templates:
      - operation: copy
        path: "gcs:/skippy-kustomization-templates/integrations/endpoint/base"
      - operation: copy
        path: "gcs:/skippy-kustomization-templates/integrations/endpoint/components/gpu"
      - operation: template
        path: "gcs:/skippy-kustomization-templates/integrations/endpoint/template"
    hashes: []

  - group: model.skippy.io
    version: v1
    kind: Monitor
    references:
      - group: model.skippy.io
        version: v1
        kind: Endpoint
        paths:
          name: spec.endpoint.name
          namespace: spec.endpoint.namespace
    templates:
      - operation: template
        path: "gcs:/skippy-kustomization-templates/integrations/monitor/template"
    hashes: []
  