apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaggle-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaggle-agent
  template:
    metadata:
      labels:
        app: kaggle-agent
    spec:
      serviceAccount: skippy-controller-manager #adk-ray-agent-sa
      containers:
      - name: agent-container
        image: us-east4-docker.pkg.dev/vicenteferrara-gke-dev/sandbox-repo/kaggle-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          value: ""
        # - name: E2B_API_KEY
        #   value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: kaggle-agent-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: kaggle-agent